Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"
config.vm.provider "virtualbox" do |vb|
  vb.memory = "512" 
end
config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get -y install apache2
  sudo apt-get -y install ufw
  sudo ufw enable
  sudo ufw allow 80/tcp
  sudo apt-get -y install ntfs-utils
  sudo systemctl start rpcbind
  sudo systemctl enable rpcbind
  sudo systemctl start nfs-server
  sudo systemctl enable nfs-server
  sudo mkdir /data
SHELL
end
