Vagrant.configure(2) do |config|
  config.vm.define "web_and_nfs" do |wn|
    wn.vm.box = "ubuntu/bionic64"
    wn.vm.hostname = 'vm1'
    wn.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    wn.vm.network "forwarded_port", guest:2049, host:2049, auto_correct: true
    wn.vm.network "private_network", ip: "192.168.10.20"
    wn.vm.synced_folder ".", "/var/www/html"
    wn.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" 
      vb.cpus = "1"
    end
    wn.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
    SHELL
    wn.vm.provision "shell", path: "apache_conf.sh"
    wn.vm.provision "shell", path: "nfs_conf.sh"
    wn.vm.provision "file", source: "~/web_input.html", destination: "/var/www/html/web_input.html"
  end

  config.vm.define "test" do |tt|
    tt.vm.box = "ubuntu/bionic64"
    tt.vm.hostname = 'vm2'
    tt.vm.network "private_network", ip: "192.168.10.30"
    tt.vm.provider "virtualbox" do |v|
      v.memory = "1024"
      v.cpus = "1"
    end
  end
end